In [2]:
import numpy as np

#Multi-dimensional arrays

#2D Array
arr2D = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2D)
print(np.sum(arr2D))

# sum_of_columns
sum_of_columns = np.sum(arr2D, axis = 0)
print(sum_of_columns)

#sum_of_rows
sum_of_rows = np.sum(arr2D, axis = 1)
print(sum_of_rows)

#slice
print(arr2D[0:2, 1:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]
[ 6 15 24]
[[2]
 [5]]


In [10]:
# 3D Array
arr3D = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]) #2 x 2 x 3
print(arr3D, arr3D.shape)

#Indexing
print(arr3D[0, 1, 1])
print(arr3D[1, 0, 2])

#Slicing
print(arr3D[:, 0, :]) # first row from both layers
print(arr3D[:, :, 0]) # first columns from both layers

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]] (2, 2, 3)
5
9
[[1 2 3]
 [7 8 9]]
[[ 1  4]
 [ 7 10]]
