In [3]:
import numpy as np

#Vectorization
arr = np.array([1, 2, 3, 4, 5])
arr2 = np.array([6, 7, 8, 9, 10])
squares = arr ** 2
print(arr)
print(squares)
print(arr + 10)
print(arr + arr2)

[1 2 3 4 5]
[ 1  4  9 16 25]
[11 12 13 14 15]
[ 7  9 11 13 15]
